// src/app/app.component.ts
import { Component } from '@angular/core';
import { environment } from 'src/environments/environment';
import { PhraseGenerator } from './models/phrase-generator';

import {
	getDefaultGeneratorOptions,
	PhraseGenerationOptions
} from './models/phrase-generator-options';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css']
})
export class AppComponent {

	private readonly generator = new PhraseGenerator();

	// TODO: add UI controls for customizable options
	public generatorOptions: PhraseGenerationOptions = getDefaultGeneratorOptions();
	public generatedPhrases: string[] = [];
	public lastCopiedPhrase: string = '';
	public phraseCount: number = 10;

	constructor() {
		this.regenerate();
	}

	public get appVersion(): string {
		return environment.version;
	}

	public async copyToClipboard(value: string): Promise<void> {
		await navigator.clipboard.writeText(value);
		this.lastCopiedPhrase = value;
	}

	public regenerate(): void {
		this.generatedPhrases = [];
		for (let i = 0; i < this.phraseCount; i++)
			this.generatedPhrases[i] = this.createNewPhrase();
	}

	private createNewPhrase(): string {
		return this.generator.generate(this.generatorOptions);
	}
}

<div class="content-wrapper" role="main">

	<div class="header">
		<div class="header-inner">

			<h1 class="title">
				Phrag
			</h1>

			<button class="settings-button" (click)="toggleShowSettings()">
				<mat-icon>settings</mat-icon>
			</button>

		</div>
	</div>

	<div class="settings" [class.visible]="showSettings">
		<div class="settings-inner">

			<div class="setting-option">
				<label>Use Characters <app-charset [chars]="extraSpecialChars"></app-charset>
				</label>
				<input type="checkbox" [(ngModel)]="includeAllSpecialCharacters" />
			</div>

		</div>
	</div>

	<div class="content">
		<div class="content-inner">

			<ng-template #loading>
				<div class="loading">
					Loading...
				</div>
			</ng-template>

			<ng-container *ngIf="didInitialize; else loading">

				<button class="regenerate-button" (click)="regenerate()">
					Regenerate
				</button>

				<div class="phrase-generation-output">
					<div class="phrase-row" *ngFor="let phrase of generatedPhrases">
						<div class="phrase-value-col" [class.last-copied-value]="phrase === lastCopiedPhrase">
							{{phrase}}
						</div>
						<div class="phrase-copy-button-col">
							<button (click)="copyToClipboard(phrase)">
								{{phrase === lastCopiedPhrase ? 'Copied!' : 'Copy'}}
							</button>
						</div>
					</div>
				</div>

			</ng-container>

		</div>
	</div>

	<div class="footer" *ngIf="didInitialize">
		<div class="footer-inner">
			<a class="version-button-container" href="https://github.com/jospete/obsidize-phrag">
				<button class="version-button">
					<img class="version-button-icon" src="./assets/icons/github-mark.svg" />
					<label class="version-button-label">Version {{appVersion}}</label>
				</button>
			</a>

		</div>
	</div>

</div>

// projects/phrag-react/src/App.tsx
import { useState } from 'react';
import { Settings } from '@mui/icons-material';
import './App.css';

function App() {
	const [showSettings, setShowSettings] = useState(false);
	const [initialized, setInitialized] = useState(false);
	const [lastCopiedPhrase, setLastCopiedPhrase] = useState('');
	const [generatedPhrases, setGeneratedPhrases] = useState([]);
	const [includeAllSpecialCharacters, setIncludeAllSpecialCharacters] = useState(false);
	const extraSpecialChars: string[] = [];
	const appVersion = '1.0.0';

	const toggleShowSettings = () => {
	};

	const regenerate = () => {
	};

	const copyToClipboard = () => {
	};

	const handleIncludeAllSpecialCharactersChange = () => {
	};

  return (
	<div className="content-wrapper" role="main">
		<div className="header">
			<div className="header-inner">
				<h1 className="title">
					<img src="./assets/icons/favicon-32x32.png" />
					<span className="title-text">(Phra)se (G)enerator</span>
				</h1>
				<button className="settings-button" onClick={toggleShowSettings}>
					<Settings />
				</button>
			</div>
		</div>
		<div className={"settings" + (showSettings ? 'visible' : '')}>
			<div className="settings-inner">
				<div className="setting-option">
					<div className="settings-option-label-wrapper">
						<label>Use Advanced Characters</label>
						<div className="charset-block">
							{extraSpecialChars.map(c => (<span className="char-block">{c}</span>))}
						</div>
					</div>
					<input type="checkbox" checked={includeAllSpecialCharacters} onChange={handleIncludeAllSpecialCharactersChange} />
				</div>
			</div>
		</div>
		<div className="content">
			<div className="content-inner">
				{!initialized &&
				<div className="loading">
						Loading...
				</div>
				}
				{initialized &&
				<>
					<button className="regenerate-button" onClick={regenerate}>
						Regenerate
					</button>
					<div className="phrase-generation-output">
						{generatedPhrases.map(phrase => (
							<div className="phrase-row">
								<div className={"phrase-value-col" + (phrase === lastCopiedPhrase ? "last-copied-value": "")}>
									{phrase}
								</div>
								<div className="phrase-copy-button-col">
									<button onClick={copyToClipboard}>
										{phrase === lastCopiedPhrase ? 'Copied!' : 'Copy'}
									</button>
								</div>
							</div>
						))}
					</div>
				</>
				}
			</div>
		</div>
		{initialized &&
		<div className="footer">
			<div className="footer-inner">
				<a className="version-button-container" target="_blank" href="https://github.com/jospete/obsidize-phrag">
					<button className="version-button">
						<img className="version-button-icon" src="./assets/icons/github-mark.svg" />
						<label className="version-button-label">Version {appVersion}</label>
					</button>
				</a>
			</div>
		</div>
		}
	</div>
  )
}

export default App
